### ISSUE TITLE
Po aktualizacji nadal nie działa.

### ISSUE THREAD

**Issue by NoName12121212** [FunnyGuilds/FunnyCreator#10]
Gdy uruchomiłem najnowszą wersję FunnyCreator'a program przez dłuższy czas pracuje po czym wyświetla taki błąd:
https://scr.hu/rY8opl

**Comment by dzikoysk** [comment]
Ok, a spróbuj odpalić z cmd przez `java -jar funnycreator-1.0.7.jar` i podaj cały log, który Ci wyrzuci

**Comment by NoName12121212** [comment]
https://hastebin.com/wugohayuju.sql

**Comment by dzikoysk** [comment]
Masz zainstalowane [JDK8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)?

**Comment by NoName12121212** [comment]
Wydaje mi się, że tak xD
https://scr.hu/vvp7zn

**Comment by dzikoysk** [comment]
Masz to na dysku `C` czy jakiś inny?

**Comment by NoName12121212** [comment]
c

**Comment by kacperduras** [comment]
15300497d74c5806b8133755d5be01408b4ddb4e
