### ISSUE TITLE
Błędy przy włączaniu.

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyCreator#2]
Tutaj łapcie ssa ;x, (błędy przy włączaniu)
![bez tytulujhjhjh](https://user-images.githubusercontent.com/32819810/32250658-b910871a-be8d-11e7-87b1-bb597ac5fbb1.png)

**Comment by kacperduras** [comment]
Uruchamiałeś jako administrator?

**Comment by dzikoysk** [comment]
Czemu odpalasz to w katalogu systemowym xD

**Comment by DrejkBR** [comment]
@kacperduras 
@dzikoysk 
Witam, nie mam opcji: Uruchom jako Administrator.
Co do wypowiedzi dzika to nie zrozumiałem...

**Comment by dzikoysk** [comment]
FunnyCreator jest odpalany w `C:\Windows\system32` więc nic dziwnego, że się wysypuje jak nie ma dostępu do tego katalogu. W jaki sposób uruchamiasz apke i gdzie się ona znajduje?

**Comment by DrejkBR** [comment]
@dzikoysk 
Znajduję cie na dysku C (pulpit) po prostu klikam dwa razy na plik (jar) albo za pomoca javy otwieram,

**Comment by dzikoysk** [comment]
Wypróbuj wersję [1.0.4](https://github.com/FunnyGuilds/FunnyCreator/releases/tag/1.0.4), powinno pomóc

**Comment by dzikoysk** [comment]
https://github.com/FunnyGuilds/FunnyCreator/commit/129340df8d72ed645948749954dcc3eee595810d
