### ISSUE TITLE
Problem z FunnyCreatorem

### ISSUE THREAD

**Issue by MentosPL** [FunnyGuilds/FunnyCreator#3]
Mam mały problem z FunnyCreatorem, nie za bardzo mi chce działać, mimo posiadania JDK x32 oraz x64.

http://prntscr.com/h63yv6

Po tym błędzie, który wyświetla się przez 0.5 sekundy, ładuje mi się strona z linkami do pobrania JDK ;-;

**Comment by dzikoysk** [comment]
Którą wersję FunnyCreatora masz?

**Comment by MentosPL** [comment]
1.0.1

**Comment by dzikoysk** [comment]
A no właśnie, aktualnie jest już wersja 1.0.4 -> https://github.com/FunnyGuilds/FunnyCreator/releases
Spróbuj na niej i jak coś będzie dalej sypać, to daj znać w nowym issue :)

**Comment by MentosPL** [comment]
Naprawione w wersji 1.0.5 :D 
https://dzikoysk.net/projects/funnycreator/download/1.0.5/funnyguilds-creator-1.0.5.jar
