### ISSUE TITLE
Znowu błędy idk.

### ISSUE THREAD

**Issue by DrejkBR** [FunnyGuilds/FunnyCreator#4]
Mam znowu błędy  ;c
Otwieram na dysku C za pomocą javy: 
![przy otwieraniu za pomoca javy](https://user-images.githubusercontent.com/32819810/32413642-303d2d12-c216-11e7-81dd-647f0363e2e4.png)

A tutaj błędy jak otwieram jak klikam dwa razy tylko.
![dwa razy](https://user-images.githubusercontent.com/32819810/32413646-4efeb9aa-c216-11e7-8132-e5dd9bd61689.png)

**Comment by dzikoysk** [comment]
1. Nie odpalaj apki ręcznie, bo robisz to źle. Proces Javy ma base.dir w `C:\Windows\system32`, więc to normalne, że nie pozwala tworzyć katalogów
2. Drugi problem wynika z tego, że FC nie może nawiązać połączenia z githubem.

Sprawdź tą wersję: 
[funnyguilds-creator-1.0.6.zip](https://github.com/FunnyGuilds/FunnyCreator/files/1443944/funnyguilds-creator-1.0.6.zip)

**Comment by DrejkBR** [comment]
@dzikoysk 
Nie rozumiem, jak mam otwierać za pomocą javy bo nie rozumiem,,,

**Comment by dzikoysk** [comment]
Po prostu uruchom FC dwuklikiem (jak na drugim screenie), a nie przez cmd/za pomocą

**Comment by DrejkBR** [comment]
@dzikoysk 
Wszystko działa tylko, nie wiem dlaczego ale musiałem wyłączyć zaporę (avast) tak samo mam jak chcę grać na serwer na np. wersji 1.10 co przychodzi mi do głowy to java...
