### ISSUE TITLE
Funny Creator 1.0.6 nie dziala pomocy!! 2018-03-01 15:45

### ISSUE THREAD

**Issue by T0fficzeG** [FunnyGuilds/FunnyCreator#5]
Pobralem jdk 8 - Po wlaczeinu tego wyswietla mi sie wszystko okej ale wyskakuje JDK Directory - NULL
Cannot load creator

**Comment by T0fficzeG** [comment]
wyslac logi bo nie mg ich zkopiowac wiec zrb screenshota jak cos

**Comment by T0fficzeG** [comment]
Da sie jakos na tej stronce przeslac? screena

**Comment by T0fficzeG** [comment]
Mam FunnyCreato 1.0.6 JAVA JDK 8 x64 - jdk-8u161 windows x64

**Comment by dzikoysk** [comment]
Podaj dokładną ścieżkę do zainstalowanego jdk

**Comment by T0fficzeG** [comment]
mg wyslac link?

**Comment by T0fficzeG** [comment]
skad pobralem

**Comment by Kamilkime** [comment]
dzikowi chodzi o to, gdzie na komputerze dokładnie zainstalowałeś JDK

**Comment by T0fficzeG** [comment]
Java SE Development Kit 8 http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
Windows x64 jdk-8u161-windows-x64.exe
 Java SE Development Kit 8u161
aaa ok  dysk D

**Comment by T0fficzeG** [comment]
Dysk D czyli nie ten glowny

**Comment by T0fficzeG** [comment]
Czyli nie da sie nic zrobic?

**Comment by dzikoysk** [comment]
#6
