### ISSUE TITLE
Funny Creator 1.0.6 Nie dziala / Pilna pomoc !!

### ISSUE THREAD

**Issue by T0fficzeG** [FunnyGuilds/FunnyCreator#6]
Informacje:
Java Se Development Kit 8 windows 64x 8u161 rozmiar 206.51 MB
Windows 7
JDK zainstalowane na dysku D [Nie glowny]
Logi:
https://imgur.com/a/QYjdx
FunnyGuilds Creator 1.0.6
Jave pobralem z http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
Dodatkowe informacje
Wyswietla mi sie Java Directory = Null

**Comment by T0fficzeG** [comment]
potrzebuje pomocy , bo ranking mi nie dziala a podobno wystarczy cos zrobic z tym funnycreatorem

**Comment by dzikoysk** [comment]
Błąd FunnyCreatora związany z niestandardową instalacją jdk. Jak zainstalujesz sobie na C (głównym) to powinno ruszyć

**Comment by T0fficzeG** [comment]
aaaaaaaaaaa okej

**Comment by dzikoysk** [comment]
Pobierz wersję `1.0.7`, jeżeli błąd dalej występuje, to otwórz nowe zgłoszenie
